import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@/app/globals.css';
import '@/app/transition.css';
import SideBar from '@/app/components/SideBar/SideBar';
import Main from '@/app/components/Main';
// import generateSearchIndex from '@/lib/generateSearchIndex';
import fs from 'fs';
import path from 'path';
// 字体配置
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});
// 元数据
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

//  根布局
export default async function RootLayout({
  children,
}: Readonly<{
  // 用于将对象的所有属性设置为只读（不可修改）
  children: React.ReactNode;
}>) {
  // 生成搜索索引 - 主要负责生成 md文件的搜索索引
  // await generateSearchIndex();
  //  此处使用的为啥是根目录路径 ？
  // const res = await fs.promises.readFile(
  //   path.join(process.cwd(), '/public/SearchIndex/search-index.json'),
  //   'utf-8',
  // );
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} body antialiased`}
      >
        <div id="root" className="flex-1">
          <SideBar className={'sidebar'}></SideBar>
          <Main>{children}</Main>
        </div>
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
